spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 607499492139-lnq9ef3kreo6dmnj1eabi30q98fklofn.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          github:
            clientId: a0a377a79d35e115c1ef
            clientSecret: 1f6f099272ec793f69371890c56363a84f32c932
            scope:
              - name
              - email
              - avatar_url
  h2:
    console:
      enabled: true
